name: Generate TOC

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install markdown-toc
        run: npm install -g markdown-toc

      - name: Generate TOC
        run: markdown-toc -i README.md

      - name: Normalize list bullets to dashes
        run: |
          sed -i 's/^[[:space:]]*[*+]/  -/g' README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update TOC (dash style)" || echo "No changes to commit"
          git push
