name: Generate TOC

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install doctoc
        run: npm install -g doctoc

      - name: Generate TOC with dashes
        run: doctoc README.md --github --notitle --list-type dash

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update TOC" || echo "No changes to commit"
          git push
